In [1]:
import numpy as np 
import pandas as pd

In [2]:
df =  pd.read_html('https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M')
df

[    Postal Code           Borough  \
 0           M1A      Not assigned
 1           M2A      Not assigned
 2           M3A        North York
 3           M4A        North York
 4           M5A  Downtown Toronto
 ..          ...               ...
 175         M5Z      Not assigned
 176         M6Z      Not assigned
 177         M7Z      Not assigned
 178         M8Z         Etobicoke
 179         M9Z      Not assigned

                                          Neighbourhood
 0                                         Not assigned
 1                                         Not assigned
 2                                            Parkwoods
 3                                     Victoria Village
 4                            Regent Park, Harbourfront
 ..                                                 ...
 175                                       Not assigned
 176                                       Not assigned
 177                                       Not assigned
 178  Mimico NW, The Queensway West, South of Bloor,...
 179                                       Not assigned

 [180 rows x 3 columns],
                                                   0   \
 0                                                NaN
 1  NL NS PE NB QC ON MB SK AB BC NU/NT YT A B C E...
 2                                                 NL
 3                                                  A

                                                   1   \
 0                              Canadian postal codes
 1  NL NS PE NB QC ON MB SK AB BC NU/NT YT A B C E...
 2                                                 NS
 3                                                  B

                                                   2    3    4    5    6    7   \
 0                                                NaN  NaN  NaN  NaN  NaN  NaN
 1  NL NS PE NB QC ON MB SK AB BC NU/NT YT A B C E...  NaN  NaN  NaN  NaN  NaN
 2                                                 PE   NB   QC   QC   QC   ON
 3                                                  C    E    G    H    J    K

     8    9    10   11   12   13   14   15     16   17
 0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    NaN  NaN
 1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    NaN  NaN
 2   ON   ON   ON   ON   MB   SK   AB   BC  NU/NT   YT
 3    L    M    N    P    R    S    T    V      X    Y  ,
    0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15     16  17
 0  NL  NS  PE  NB  QC  QC  QC  ON  ON  ON  ON  ON  MB  SK  AB  BC  NU/NT  YT
 1   A   B   C   E   G   H   J   K   L   M   N   P   R   S   T   V      X   Y]

In [7]:
df1

,Postal Code,Borough,Neighbourhood
0,M1A,Not assigned,Not assigned
1,M2A,Not assigned,Not assigned
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,"Regent Park, Harbourfront"
...,...,...,...
175,M5Z,Not assigned,Not assigned
176,M6Z,Not assigned,Not assigned
177,M7Z,Not assigned,Not assigned
178,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."
179,M9Z,Not assigned,Not assigned

Below cell will ignore the Borough that contains 'Not assigned' ans assign to 'df1' dataframe

In [8]:
df1 = df1[ df1.Borough != 'Not assigned']

In [9]:
df1

,Postal Code,Borough,Neighbourhood
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,"Regent Park, Harbourfront"
5,M6A,North York,"Lawrence Manor, Lawrence Heights"
6,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government"
...,...,...,...
160,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North"
165,M4Y,Downtown Toronto,Church and Wellesley
168,M7Y,East Toronto,"Business reply mail Processing Centre, South C..."
169,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu..."
178,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."

Below cell will check if If a cell has a borough but a Not assigned neighborhood, then the neighborhood will be the same as the borough.

In [10]:
df1[df1.Neighbourhood == 'Not assigned']

Empty DataFrame
Columns: [Postal Code, Borough, Neighbourhood]
Index: []

Below cell will find out the shape of dataframe

In [12]:
df1.shape

(103, 3)

In [13]:
df_latlong = pd.read_csv('Geospatial_Coordinates.csv')
df_latlong

    Postal Code   Latitude  Longitude
0           M1B  43.806686 -79.194353
1           M1C  43.784535 -79.160497
2           M1E  43.763573 -79.188711
3           M1G  43.770992 -79.216917
4           M1H  43.773136 -79.239476
..          ...        ...        ...
98          M9N  43.706876 -79.518188
99          M9P  43.696319 -79.532242
100         M9R  43.688905 -79.554724
101         M9V  43.739416 -79.588437
102         M9W  43.706748 -79.594054

[103 rows x 3 columns]

In [17]:
df1['Latitude']

2      1
3      1
4      1
5      1
6      1
      ..
160    1
165    1
168    1
169    1
178    1
Name: Latitude, Length: 103, dtype: int64

In [22]:
df1

,Postal Code,Borough,Neighbourhood,Latitude,Longitude
2,M3A,North York,Parkwoods,1,1
3,M4A,North York,Victoria Village,1,1
4,M5A,Downtown Toronto,"Regent Park, Harbourfront",1,1
5,M6A,North York,"Lawrence Manor, Lawrence Heights",1,1
6,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government",1,1
...,...,...,...,...,...
160,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North",1,1
165,M4Y,Downtown Toronto,Church and Wellesley,1,1
168,M7Y,East Toronto,"Business reply mail Processing Centre, South C...",1,1
169,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu...",1,1
178,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,...",1,1

below algorith assign each latitude,longitude of df_latlong to correspond postal code in df1 dataframe

In [49]:
for i in range(103):
    for j in range(103):
         if (df_latlong.iloc[i,0] == df1.iloc[j,0]) :
                df1.iloc[j,3] = df_latlong.iloc[i,1]
                df1.iloc[j,4] = df_latlong.iloc[i,2]
                break

[    Postal Code           Borough  \
 0           M1A      Not assigned
 1           M2A      Not assigned
 2           M3A        North York
 3           M4A        North York
 4           M5A  Downtown Toronto
 ..          ...               ...
 175         M5Z      Not assigned
 176         M6Z      Not assigned
 177         M7Z      Not assigned
 178         M8Z         Etobicoke
 179         M9Z      Not assigned

                                          Neighbourhood
 0                                         Not assigned
 1                                         Not assigned
 2                                            Parkwoods
 3                                     Victoria Village
 4                            Regent Park, Harbourfront
 ..                                                 ...
 175                                       Not assigned
 176                                       Not assigned
 177                                       Not assigned
 178  Mimico NW, The Queensway West, South of Bloor,...
 179                                       Not assigned

 [180 rows x 3 columns],
                                                   0   \
 0                                                NaN
 1  NL NS PE NB QC ON MB SK AB BC NU/NT YT A B C E...
 2                                                 NL
 3                                                  A

                                                   1   \
 0                              Canadian postal codes
 1  NL NS PE NB QC ON MB SK AB BC NU/NT YT A B C E...
 2                                                 NS
 3                                                  B

                                                   2    3    4    5    6    7   \
 0                                                NaN  NaN  NaN  NaN  NaN  NaN
 1  NL NS PE NB QC ON MB SK AB BC NU/NT YT A B C E...  NaN  NaN  NaN  NaN  NaN
 2                                                 PE   NB   QC   QC   QC   ON
 3                                                  C    E    G    H    J    K

     8    9    10   11   12   13   14   15     16   17
 0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    NaN  NaN
 1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    NaN  NaN
 2   ON   ON   ON   ON   MB   SK   AB   BC  NU/NT   YT
 3    L    M    N    P    R    S    T    V      X    Y  ,
    0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15     16  17
 0  NL  NS  PE  NB  QC  QC  QC  ON  ON  ON  ON  ON  MB  SK  AB  BC  NU/NT  YT
 1   A   B   C   E   G   H   J   K   L   M   N   P   R   S   T   V      X   Y]

In [53]:
df1 =df1.reset_index()

df1

,index,Postal Code,Borough,Neighbourhood,Latitude,Longitude
0,2,M3A,North York,Parkwoods,43.753259,-79.329656
1,3,M4A,North York,Victoria Village,43.725882,-79.315572
2,4,M5A,Downtown Toronto,"Regent Park, Harbourfront",43.654260,-79.360636
3,5,M6A,North York,"Lawrence Manor, Lawrence Heights",43.718518,-79.464763
4,6,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government",43.662301,-79.389494
...,...,...,...,...,...,...
98,160,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North",43.653654,-79.506944
99,165,M4Y,Downtown Toronto,Church and Wellesley,43.665860,-79.383160
100,168,M7Y,East Toronto,"Business reply mail Processing Centre, South C...",43.662744,-79.321558
101,169,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu...",43.636258,-79.498509
102,178,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,...",43.628841,-79.520999

In [54]:
df1.drop(['index'] , axis = 1 , inplace = True)
df1

,Postal Code,Borough,Neighbourhood,Latitude,Longitude
0,M3A,North York,Parkwoods,43.753259,-79.329656
1,M4A,North York,Victoria Village,43.725882,-79.315572
2,M5A,Downtown Toronto,"Regent Park, Harbourfront",43.654260,-79.360636
3,M6A,North York,"Lawrence Manor, Lawrence Heights",43.718518,-79.464763
4,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government",43.662301,-79.389494
...,...,...,...,...,...
98,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North",43.653654,-79.506944
99,M4Y,Downtown Toronto,Church and Wellesley,43.665860,-79.383160
100,M7Y,East Toronto,"Business reply mail Processing Centre, South C...",43.662744,-79.321558
101,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu...",43.636258,-79.498509
102,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,...",43.628841,-79.520999